### ISSUE TITLE
"Loadable" SynthDefs

### ISSUE THREAD

**Issue by meznom** [SCLOrkHub/SCLOrkSynths#2]
From my point of view it would be nice if the SynthDefs in the repository were directly loadable, i.e. the files could be included with SuperCollider's "load" and "loadRelative". This way one could simply clone the repository and then directly import and play around with the SynthDefs by calling, e.g. 

```
loadRelative("SynthDefs-for-Patterns/blips.scd");
```

Right now not all files can be loaded like this and some play the included demo patterns upon loading.

For directly loadable SynthDefs I would suggest
- one SynthDef per file, where the filename is identical to the SynthDef name
- demo patterns can populate a global dictionary, e.g. `~synthDemos["blips"].play` would play the blips SynthDef demo pattern

These are just some ideas. To get a better feeling of how this would work out in practice I've partially implemented and tested them in a [new branch](https://github.com/meznom/SynthDefs-for-Patterns/tree/file_reorganization). I've also experimented with organizing the files into modules and submodules which can be "loaded" via a `initmodule.scd`file (this certainly needs refinement). Lastly, I've thrown together a quick GUI for playing all the demo patterns (`~synthDemoGui`). If you consider some of these ideas worth pursuing, I could create a pull request.

By the way, I've had a lot of fun playing around with the SynthDefs, so thanks a lot for putting them up on GitHub. Such a SynthDef collection repository is definitely super useful.

**Comment by brunoruviaro** [comment]
Hi again, and sorry for the silence since Oct '14! This Summer I will finally have time to give this project a strong push. I plan to add a bunch of new SynthDefs in the coming weeks. Your suggestions are good -- go ahead and create a pull request, and we'll go from there. Let's keep experimenting to find out what makes sense. Thanks!

**Comment by brunoruviaro** [comment]
Six years later, SCLOrkSynths has finally come around and been released, including a collection of demo patterns and a GUI as @meznom originally suggested in 2014! Thanks! :-)
