### ISSUE TITLE
ksbass: Change envelope definition

### ISSUE THREAD

**Issue by brunoruviaro** [SCLOrkHub/SCLOrkSynths#84]
https://github.com/SCLOrkHub/SCLOrkSynths/blob/efcb4fb885ea8de1643713c7f638b5156b89aba5/SynthDefs/bass/ksbass.scd#L42-L45

Use Env.new instead, to clarify the importance of impulseHold. Something like:
`Env.new(
		levels: [0, 1, 1, 0, 0],
		times: [impulseAtt, impulseSus, impulseDec, impulseHold]
	)`

Also update arg names as you did in Google Doc (impulseAtt, impulseSus, impulseDec, impulseHold).

**Comment by joshmit** [comment]
Done! I also updated the respective demo.

**Comment by brunoruviaro** [comment]
ps note you can also refer to the commit where you resolved it (to allow for quick reference) -- simply copy the commit hash into the comment.
your kbass update is here - 0b922fc6fc694345ba6f4090055bbe112a527f88
and your kbass demo update is here - 3fc5c479f7b1004da5049af687587beab4c8d364
