### ISSUE TITLE
Fix this, Josh

### ISSUE THREAD

**Issue by joshmit** [SCLOrkHub/SCLOrkSynths#85]
https://github.com/SCLOrkHub/SCLOrkSynths/blob/2758d695d78f548c048d0eea2d4c07ff50c8bb3d/SynthDefs/keyboards/harpsichord2.scd#L19

**Comment by unthingable** [comment]
Yes, fix it!

**Comment by joshmit** [comment]
Fixed

**Comment by unthingable** [comment]
:-D

I thought you would enjoy a comment from a random attentive stranger.

**Comment by brunoruviaro** [comment]
nice gentle pressure
