### ISSUE TITLE
GUI does not launch

### ISSUE THREAD

**Issue by MackieBlackburn** [SCLOrkHub/SCLOrkSynths#95]
Trying to open the GUI on Windows PC gives the following error:

`ERROR: Message '+/+' not understood.
RECEIVER:
   nil
ARGS:
Instance of String {    (000002398F6F6700, gc=01, fmt=07, flg=11, set=02)
  indexed slots [9]
      0 : S
      1 : y
      2 : n
      3 : t
      4 : h
      5 : D
      6 : e
      7 : f
      8 : s
}
PATH: C:/Users/Mack/Downloads/SCLOrkSynths-master/SCLOrkSynths-master/SCLOrkSynths.sc
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = '+/+'
		arg args = [*1]
	Meta_SCLOrkSynths:gui
		arg this = <instance of Meta_SCLOrkSynths>
		var header = nil
		var gap = 5
		var margin = 10
		var banksMenu = nil
		var currentBank = 'drums'
		var numberOfColumns = 5
		var numberOfRows = 10
		var windowWidth = 800
		var windowHeight = 480
		var buttonWidth = 152.0
		var buttonHeight = 25
		var buttonArray = nil
		var activeButton = nil
		var footer1 = nil
		var footer2 = nil
		var currentSynth = nil
		var currentSynthText = nil
		var banks = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "SCLOrkSynths.gui"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message '+/+' not understood.
RECEIVER: nil
`

**Comment by brunoruviaro** [comment]
I just tried on SC 3.11 / Windows 10, and it works for me. What SC version are you running?

Is it just the GUI that is not working? (what happens if you run ``SCLOrkSynths.load``?

**Comment by MackieBlackburn** [comment]
This is the output I get from running SCLOrkSynths.load. It seems to be working but it also says "0 SynthDefs available"
`
Booting server 'localhost' on address 127.0.0.1:57110.

Device options:
  - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Microphone (Steam Streaming Mic   (device #1 with 8 ins 0 outs)
  - MME : Microsoft Sound Mapper - Output   (device #2 with 0 ins 2 outs)
  - MME : Speakers (Realtek High Definiti   (device #3 with 0 ins 8 outs)
  - MME : Realtek Digital Output (Realtek   (device #4 with 0 ins 2 outs)
  - MME : Speakers (Steam Streaming Speak   (device #5 with 0 ins 8 outs)
  - MME : Speakers (Steam Streaming Micro   (device #6 with 0 ins 8 outs)
  - Windows DirectSound : Primary Sound Capture Driver   (device #7 with 2 ins 0 outs)
  - Windows DirectSound : Microphone (Steam Streaming Microphone)   (device #8 with 8 ins 0 outs)
  - Windows DirectSound : Primary Sound Driver   (device #9 with 0 ins 8 outs)
  - Windows DirectSound : Speakers (Realtek High Definition Audio)   (device #10 with 0 ins 8 outs)
  - Windows DirectSound : Realtek Digital Output (Realtek High Definition Audio)   (device #11 with 0 ins 2 outs)
  - Windows DirectSound : Speakers (Steam Streaming Speakers)   (device #12 with 0 ins 8 outs)
  - Windows DirectSound : Speakers (Steam Streaming Microphone)   (device #13 with 0 ins 8 outs)
  - ASIO : Realtek ASIO   (device #14 with 2 ins 2 outs)
  - Windows WASAPI : Speakers (Realtek High Definition Audio)   (device #15 with 0 ins 8 outs)
  - Windows WASAPI : Realtek Digital Output (Realtek High Definition Audio)   (device #16 with 0 ins 8 outs)
  - Windows WASAPI : Speakers (Steam Streaming Speakers)   (device #17 with 0 ins 2 outs)
  - Windows WASAPI : Speakers (Steam Streaming Microphone)   (device #18 with 0 ins 2 outs)
  - Windows WASAPI : Microphone (Steam Streaming Microphone)   (device #19 with 1 ins 0 outs)
  - Windows WDM-KS : SPDIF Out (Realtek HDA SPDIF Out)   (device #20 with 0 ins 2 outs)
  - Windows WDM-KS : Line In (Realtek HD Audio Line input)   (device #21 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #22 with 0 ins 8 outs)
  - Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input)   (device #23 with 2 ins 0 outs)
  - Windows WDM-KS : Microphone (Realtek HD Audio Mic input)   (device #24 with 2 ins 0 outs)
  - Windows WDM-KS : Microphone (Steam Streaming Microphone Wave)   (device #25 with 8 ins 0 outs)
  - Windows WDM-KS : Speakers (Steam Streaming Microphone Wave)   (device #26 with 0 ins 8 outs)
  - Windows WDM-KS : Input (Steam Streaming Speakers Wave)   (device #27 with 8 ins 0 outs)
  - Windows WDM-KS : Speakers (Steam Streaming Speakers Wave)   (device #28 with 0 ins 8 outs)

Requested devices:
  In (matching device NOT found):
  - (null)
  Out (matching device NOT found):
  - (null)

Selecting default system input/output devices

Booting with:
  In: MME : Microphone (Steam Streaming Mic
  Out: MME : Speakers (Realtek High Definiti
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
SCLOrkSynths now loaded
synthDictionary was created.
0 SynthDefs available.
`

**Comment by MackieBlackburn** [comment]
> I just tried on SC 3.11 / Windows 10, and it works for me. What SC version are you running?
> 
> Is it just the GUI that is not working? (what happens if you run `SCLOrkSynths.load`?

**Comment by MackieBlackburn** [comment]
It would be helpful if this repo had a sentence or two for installation instructions. I've put the folder in the "extensions" folder for SuperCollider and also tried loading it using quarks but both seemed to have the same error.

**Comment by brunoruviaro** [comment]
Can you try this? (it will remove any prior installation of SCLOrkSynths, then try again using the instructions I just added to the github page):
```
// Attempt to uninstall through code
Quarks.uninstall("SCLOrkSynths");
```
Now go to the Quarks folder (`Quarks.openFolder;`), then manually delete any SCLOrkSynths folder there
(whether it's "SCLOrkSynths" or "SCLOrkSynths-master", delete them all).


Now go to SuperCollider Preferences (from the menus), then under "Interpreter", remove any SCLOrkSynths path that you see in the "include:" box. Simply select the path you want to delete and hit the 'minus' button.

At this point, all prior installations of SCLOrkSynths should be gone. Restart SuperCollider now.

After restarting SC, run these lines one at a time:

`Quarks.fetchDirectory;`
`Quarks.install("SCLOrkSynths");`

Restart SuperCollider again (or simply recompile class library from the Language menu).

Hopefully now `SCLOrkSynths.gui` will work. Let me know.

**Comment by MackieBlackburn** [comment]
I found out I had an issue with Git on my computer and Quarks were not working properly. After fixing that I was able to install this and it works fine thank you.
